[tool.black]
target-version = ['py37']
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.mypy_cache
    | venv
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 88
skip_glob = ['venv']
combine_as_imports = true
combine_star = true
known_third_party = ['pydantic', 'mock']
know_standard_library = ['json']
